import type { Metadata } from 'next';
import { Fira_Code } from 'next/font/google';
import { cn } from '@/lib/utils';
import Header from '@/components/header.component';
import Providers from '@/providers/index.provider';
import './globals.css';

const FiraCode = Fira_Code({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(
          FiraCode.className,
          'min-h-screen bg-background font-sans antialiased'
        )}
      >
        <Providers>
          <div className='relative flex min-h-dvh flex-col bg-background'>
            <Header />
            <main className='flex-1'>{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
